version: 2

sources: 
  - name: gz_raw_data
    description: whole data set
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: greens sales
      - name: raw_gz_product
        description: green products
      - name: raw_gz_ship
        description: green ship
