version: 2

sources: 
  - name: gz_raw_data
    description: whole data set
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: greens sales
      - name: product
        identifier: raw_gz_product
        description: green products
      - name: shop
        identifier: raw_gz_ship
        description: green ship
      - name: adwords
        identifier: raw_gz_adwords
        description: green ads
      - name: bing
        identifier: raw_gz_bing
        description: green bing
      - name: criteo
        identifier: raw_gz_criteo
        description: green criteo
      - name: facebook
        identifier: raw_gz_facebook
        description: green facebook